Feature issue remove rename sheet
tealeg/xlsx pull request #615
Opened 2020-08-25 10:26 UTC by rentiansheng

### feature 

- remove a sheet from file #590
- rename a sheet from file  #602

close #590 #602

2020-09-09 13:16 UTC, Doctor-X commented on file.go
> +func (f *File) RenameSheet(oleSheetName, newSheetName string) {
In RenameSheet(), I can't see where sheet is getting initialized

2020-09-09 13:35 UTC, tealeg requested changes
It looks good in principle, there's a couple of little tidies needed.

2020-09-09 13:35 UTC, tealeg commented on file.go
> +func (f *File) RenameSheet(oleSheetName, newSheetName string) {
I believe `oleSheetName` should be `oldSheetName`.

2020-09-09 13:35 UTC, tealeg commented on file.go
> +	if sheet != nil {
This block will never run, as `sheet` is never set.

2020-09-09 13:54 UTC, Doctor-X commented on file_test.go
> +func (l *FileSuite) TesRenameheet(c *C) {
This function will never be executed, should be named TestRenameSheet()

2020-10-19 21:40 UTC, tealeg approved these changes

2020-10-19 21:41 UTC, merged